### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by Grinnz** [sysread/slot#1]
The namespace `slot` is currently owned by Tie::Hash::KeysMask: https://cpanmeta.grinnz.com/packages#=slot

It's clearly a private-use module in that case so it should probably be hidden from the PAUSE indexer (by placing a newline between `package` and the package name, or adding no_index metadata), and then the permissions released by the owner SCHOEJO. However, the last release was in 2008 so I'm not sure how likely this is to get fixed. If the maintainer does not respond you can ask the PAUSE admins to intervene via modules@perl.org (recommended to cc them on any communication).

**Comment by sysread** [comment]
Thanks for the tip. I'm currently debating with myself whether it's worth trying to acquire the namespace. As you noted, he hasn't been active on CPAN in a decade so I suspect he will not be inclined to jump through all of the hoops that would require. While I make up my mind on that, I'll be over [here](https://www.merriam-webster.com/thesaurus/slot).

**Comment by sysread** [comment]
I've emailed the author. It didn't bounce, so that is promising. I'll give it a couple days.

**Comment by sysread** [comment]
Decided to avoid conflict and go with `Class::Slot`.
